### ISSUE TITLE
Use browser sync plugin with vite watch

### ISSUE THREAD

**Issue by QuentiumYT** [Applelo/vite-plugin-browser-sync#11]
Hello, I'm wondering if there is a way to use this vite plugin while using the watch option (I use `vite build --watch`).
As I am using vite to build specific assets, I would need to serve in the same time my watcher rebuild the assets.

```js
/** @type {import('vite').UserConfig} */
export default {
  appType: 'custom',
  publicDir: false,
  mode: process.env.NODE_ENV,
  base: './',
  build: {
    minify: true ? process.env.NODE_ENV === 'production' : false,
    outDir: 'dist',
 },
}
```
Small part of my config

**Comment by jeffpreussner** [comment]
you can use Browsersync standard recipes to do this outside of Vite.

**Comment by QuentiumYT** [comment]
I know, that's what I'm doing but I opened a feature request to have that bundled :)

**Comment by Applelo** [comment]
Hi, I need to check what is possible to do in the `vite build --watch` context.

**Comment by QuentiumYT** [comment]
Thank you so much 😎
