### ISSUE TITLE
load scss from a <link> element.

### ISSUE THREAD

**Issue by jeffpreussner** [Applelo/vite-plugin-browser-sync#14]
Wondering if you can help me understand something. My project is using sass and loading styles with an index.scss file works fine in the locally with the Vite development server. I have index.scss loading in index.html like so:

index.html
```html
<link rel="stylesheet" href="scss/index.scss">

```

However when I proxy my remote environment I am searching and replacing my generated css file with the local scss file:
```js
      VitePluginBrowserSync({
        bs: {
          https: false,
          rewriteRules: [
            {
              match: "<body>",
              fn: function (req, res, match) {
                return `<body><script type="module">
                import RefreshRuntime from 'http://localhost:5173/@react-refresh'
                RefreshRuntime.injectIntoGlobalHook(window)
                window.$RefreshReg$ = () => {}
                window.$RefreshSig$ = () => (type) => type
                window.__vite_plugin_react_preamble_installed__ = true
              </script>
              <script type="module" src="http://localhost:5173/@vite/client"></script>
              `;
              },
            },
            {
              //replace css with scss
              match:
                '<link href="/assets/styles/index.css" media="all" rel="stylesheet" />',
              fn: function (req, res, match) {
                return '<link href="http://localhost:5173/scss/index.scss" media="all" rel="stylesheet" />';
              },
            }
          ],
          proxy: {
            target: proxy.url,
            ws: true,
          },
          notify: false,
        },
      })
```
      
The scss file loads but the styles are not applied to frontend. When I use a <script> tag instead of a <link> it works as expected. 

```js
{
              //replace css with scss
              match:
                '<link href="/assets/styles/index.css" media="all" rel="stylesheet" />',
              fn: function (req, res, match) {
                return '<script type="module" src="http://localhost:5173/scss/index.scss"></script>';
              },
            },
```
 
I assume this is because the sass loader Vite uses but I am curious as to why  <link> tags work in server mode locally but not the proxy. Not a huge issue but if l could get the links working id be able to do a simple string replacement instead of the whole tag.

**Comment by Applelo** [comment]
Hi, ViteJS needs to process SCSS files through Javascript (directly with a script like you done or an import in your JS file) to transform your SCSS file into CSS: it can't do this through a link stylesheet. 

This is not related to BrowserSync or this plugin so I close this issue ^^

Off topic: I see you have an old configuration, if you update this plugin to 3.0, don't forget to wrap your bs object with a `dev` one 😄 (see an example [here](https://github.com/Applelo/vite-plugin-browser-sync/releases/tag/v3.0.0)).
