### ISSUE TITLE
Use in Astro Project

### ISSUE THREAD

**Issue by CraigTheNerd** [Applelo/vite-plugin-browser-sync#21]
`Would` it be possible to use this plugin in an Astro project.

I tried following the Astro docs on how to install Vite plugins but I can't get it working.

Here is my astro.config.mjs

```
import { defineConfig } from 'astro/config';
import VitePluginBrowserSync from 'vite-plugin-browser-sync'

// https://astro.build/config
export default defineConfig({
    vite: {
        plugins: [
            VitePluginBrowserSync({
                dev: {
                    bs: {
                        ui: {
                            port: 8080
                        },
                        notify: false
                    }
                }
            })
        ]
    }
});
```

I would appreciate any help, thanks!

**Comment by Applelo** [comment]
Hi 👋 It seems the plugin is not working on Astro 😶 I will try to find why 🤔

**Comment by CraigTheNerd** [comment]
Thanks so much, would appreciate it if you get it working. Please keep me posted. Thanks!!!

**Comment by CraigTheNerd** [comment]
Didn't mean to close the issue, definitely still open and waiting for feedback and solution thanks

**Comment by Applelo** [comment]
I will publish a new version soon that support AstroJS. 

For the small story, Astro doesn't pass on dev `env.isPreview` so the plugin was not applied. The second problem with Astro, it uses the Vite Dev Server but doesn't use the logger from ViteJS so the plugin cannot hook and print urls information.

**Comment by Applelo** [comment]
You can try the last version, feel free to reopen this issue if necessary 😄
